language: go
go:
- 1.9
services:
- docker
script:
- make travisbuild
after_success:
- make release
env:
  - KONG_VERSION=0.11   TF_ACC=1
  - KONG_VERSION=0.11.1 TF_ACC=1
  - secure: WdxZxmO0DUJnIZMh54Ivtnnn65UiKrJ5obLY+8X7Fdc1CTMtKcxg1EFXVo1ixvvRKZJBc8IxuitogQPB4y5WiFNle7uwHCMVhpTnSd5nzy5V2zAa+uDA7BfC+4tIma3vRfI9DxM6i53n3s2vwaqzWdE3/RtcgSALpD06hGKFYFebg5D1YV9d11G2rzze4MCm0rca3oNK3clKYcR8oePJhUtBdwX/F0j2deEpw1wLBYVS8XAc13oWsiZ9j3hTAyXUtDXImIQrLCqYLgivW/hNjSsZBrfy2J1vy/xJyXF4iihyhLxnmvpc5STEBaHsJWc2dnjEYjIxfeRd1iF2ym8KNXW9R38ZFghL2bp1RzMdh3SbEHHTQOCoG927FFjyloPLJ/H7RG7SIkwwsA4m7429BWDit+S5/oBPdLtqIXvF+2vioKiBxMSoa858JfJgBdN+Oe/oVfZGTBkXEfi+af257b7VjhgbgLh4/fkOEKKMWPsm0ogsKMbHQTfnUG+beAd9hgV03z7uBon5sUJ5gCkC6XBQQ6j3qboN+gT/XCkglUTd4ySaZ2Eg2ofvy+1DFeJePIKaI7WELYUPRAI5Bes9e3MdZCbhAebGj2iEB3Gnj+5c6Vuz2l3I5Mgm7Ax6kT0BPwCl+0rF9wBXUoM/rc9QoNTZDJl4Ynkof2pr3Bzmlk8=
